# Generated by Django 3.1.1 on 2020-09-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='comentario',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='apelido',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
